/* All six 808-style voices. They share the same skeleton (trigger input,
 * two or three macro knobs with CV, one output), so the widget layout is
 * generated by a shared template and only the DSP differs. */
#include "plugin.hpp"

using namespace rddrums;


// ---- shared widget scaffolding -------------------------------------------

/** 6HP panel: knobs stacked down the middle, trigger(s) at the bottom left,
 * output bottom right. Positions in px on the 90x380 panel. */
template <typename TModule>
struct DrumWidget : ModuleWidget {
	static constexpr float W = 90.f;

	DrumWidget(TModule* module, const char* panel) {
		setModule(module);
		setPanel(createPanel(asset::plugin(pluginInstance, panel)));

		addChild(createWidget<ScrewSilver>(Vec(RACK_GRID_WIDTH, 0)));
		addChild(createWidget<ScrewSilver>(Vec(box.size.x - 2 * RACK_GRID_WIDTH, RACK_GRID_HEIGHT - RACK_GRID_WIDTH)));
	}

	void addKnobRow(int paramId, int cvInputId, float y) {
		addParam(createParamCentered<RoundBlackKnob>(Vec(W * 0.35f, y), module, paramId));
		if (cvInputId >= 0)
			addInput(createInputCentered<PJ301MPort>(Vec(W * 0.75f, y), module, cvInputId));
	}

	void addBottomRow(int trigInputId, int outId, int trig2InputId = -1) {
		addInput(createInputCentered<PJ301MPort>(Vec(W * 0.25f, 330), module, trigInputId));
		if (trig2InputId >= 0)
			addInput(createInputCentered<PJ301MPort>(Vec(W * 0.5f, 330), module, trig2InputId));
		addOutput(createOutputCentered<PJ301MPort>(Vec(W * 0.75f, 330), module, outId));
	}
};


// ---- BD-808: bass drum ----------------------------------------------------

struct BD808 : Module {
	enum ParamId { TUNE_PARAM, DECAY_PARAM, CLICK_PARAM, NUM_PARAMS };
	enum InputId { TRIG_INPUT, TUNE_INPUT, DECAY_INPUT, NUM_INPUTS };
	enum OutputId { OUT_OUTPUT, NUM_OUTPUTS };

	dsp::SchmittTrigger trig;
	float phase = 0.f;
	ExpEnv amp, pitch;
	Noise noise;
	OnePoleLP clickLp;

	BD808() {
		config(NUM_PARAMS, NUM_INPUTS, NUM_OUTPUTS, 0);
		configParam(TUNE_PARAM, 30.f, 120.f, 52.f, "Tune", " Hz");
		configParam(DECAY_PARAM, 0.05f, 1.5f, 0.45f, "Decay", " s");
		configParam(CLICK_PARAM, 0.f, 1.f, 0.35f, "Click");
		configInput(TRIG_INPUT, "Trigger");
		configInput(TUNE_INPUT, "Tune CV");
		configInput(DECAY_INPUT, "Decay CV");
		configOutput(OUT_OUTPUT, "Audio");
	}

	void process(const ProcessArgs& args) override {
		if (trig.process(inputs[TRIG_INPUT].getVoltage(), 0.1f, 1.f)) {
			amp.trigger();
			pitch.trigger();
		}
		float f0 = params[TUNE_PARAM].getValue() * std::pow(2.f, inputs[TUNE_INPUT].getVoltage() / 5.f);
		float decay = clamp(params[DECAY_PARAM].getValue() + inputs[DECAY_INPUT].getVoltage() * 0.1f, 0.05f, 2.f);

		float p = pitch.process(0.03f, args.sampleTime);
		float a = amp.process(decay, args.sampleTime);

		// Pitch sweeps from ~4x down to the fundamental; the click is a
		// burst of filtered noise riding the first milliseconds.
		float f = f0 * (1.f + 3.5f * p * p);
		phase += f * args.sampleTime;
		if (phase >= 1.f)
			phase -= 1.f;

		clickLp.setCutoff(4000.f, args.sampleRate);
		float click = clickLp.process(noise.next()) * p * p * params[CLICK_PARAM].getValue() * 2.f;

		float body = std::sin(2.f * M_PI * phase) * a;
		// Gentle tanh drive: rounder, louder, more 808.
		float out = std::tanh(1.6f * (body + click)) * 5.f;
		outputs[OUT_OUTPUT].setVoltage(out);
	}
};

struct BD808Widget : DrumWidget<BD808> {
	BD808Widget(BD808* module) : DrumWidget(module, "res/BD808.svg") {
		addKnobRow(BD808::TUNE_PARAM, BD808::TUNE_INPUT, 90);
		addKnobRow(BD808::DECAY_PARAM, BD808::DECAY_INPUT, 165);
		addKnobRow(BD808::CLICK_PARAM, -1, 240);
		addBottomRow(BD808::TRIG_INPUT, BD808::OUT_OUTPUT);
	}
};

Model* modelBD808 = createModel<BD808, BD808Widget>("BD808");


// ---- SD-808: snare drum ---------------------------------------------------

struct SD808 : Module {
	enum ParamId { TUNE_PARAM, SNAPPY_PARAM, DECAY_PARAM, NUM_PARAMS };
	enum InputId { TRIG_INPUT, TUNE_INPUT, SNAPPY_INPUT, NUM_INPUTS };
	enum OutputId { OUT_OUTPUT, NUM_OUTPUTS };

	dsp::SchmittTrigger trig;
	float ph1 = 0.f, ph2 = 0.f;
	ExpEnv shellEnv, noiseEnv;
	Noise noise;
	OnePoleHP noiseHp;
	OnePoleLP noiseLp;

	SD808() {
		config(NUM_PARAMS, NUM_INPUTS, NUM_OUTPUTS, 0);
		configParam(TUNE_PARAM, 120.f, 320.f, 185.f, "Tune", " Hz");
		configParam(SNAPPY_PARAM, 0.f, 1.f, 0.6f, "Snappy");
		configParam(DECAY_PARAM, 0.05f, 0.5f, 0.18f, "Decay", " s");
		configInput(TRIG_INPUT, "Trigger");
		configInput(TUNE_INPUT, "Tune CV");
		configInput(SNAPPY_INPUT, "Snappy CV");
		configOutput(OUT_OUTPUT, "Audio");
	}

	void process(const ProcessArgs& args) override {
		if (trig.process(inputs[TRIG_INPUT].getVoltage(), 0.1f, 1.f)) {
			shellEnv.trigger();
			noiseEnv.trigger();
		}
		float f0 = params[TUNE_PARAM].getValue() * std::pow(2.f, inputs[TUNE_INPUT].getVoltage() / 5.f);
		float snappy = clamp(params[SNAPPY_PARAM].getValue() + inputs[SNAPPY_INPUT].getVoltage() * 0.1f, 0.f, 1.f);
		float decay = params[DECAY_PARAM].getValue();

		// Two shell partials in the classic ~1:1.63 ratio.
		float shell = shellEnv.process(decay * 0.6f, args.sampleTime);
		ph1 += f0 * args.sampleTime;          if (ph1 >= 1.f) ph1 -= 1.f;
		ph2 += f0 * 1.63f * args.sampleTime;  if (ph2 >= 1.f) ph2 -= 1.f;
		float body = (std::sin(2.f * M_PI * ph1) * 0.7f + std::sin(2.f * M_PI * ph2) * 0.3f) * shell;

		noiseHp.setCutoff(700.f, args.sampleRate);
		noiseLp.setCutoff(7500.f, args.sampleRate);
		float snap = noiseLp.process(noiseHp.process(noise.next()))
			* noiseEnv.process(decay, args.sampleTime) * snappy * 2.2f;

		outputs[OUT_OUTPUT].setVoltage(std::tanh(1.4f * (body + snap)) * 5.f);
	}
};

struct SD808Widget : DrumWidget<SD808> {
	SD808Widget(SD808* module) : DrumWidget(module, "res/SD808.svg") {
		addKnobRow(SD808::TUNE_PARAM, SD808::TUNE_INPUT, 90);
		addKnobRow(SD808::SNAPPY_PARAM, SD808::SNAPPY_INPUT, 165);
		addKnobRow(SD808::DECAY_PARAM, -1, 240);
		addBottomRow(SD808::TRIG_INPUT, SD808::OUT_OUTPUT);
	}
};

Model* modelSD808 = createModel<SD808, SD808Widget>("SD808");


// ---- HH-808: hi-hats (closed + open, closed chokes open) -------------------

struct HH808 : Module {
	enum ParamId { TONE_PARAM, DECAY_PARAM, NUM_PARAMS };
	enum InputId { CH_INPUT, OH_INPUT, TONE_INPUT, NUM_INPUTS };
	enum OutputId { OUT_OUTPUT, NUM_OUTPUTS };

	dsp::SchmittTrigger chTrig, ohTrig;
	float phases[6] = {};
	ExpEnv env;
	bool open = false;
	OnePoleHP hp1, hp2;
	OnePoleLP lp;

	// The classic six slightly-inharmonic square oscillators.
	static constexpr float RATIOS[6] = {1.0f, 1.342f, 1.2312f, 1.6532f, 1.9523f, 2.1523f};

	HH808() {
		config(NUM_PARAMS, NUM_INPUTS, NUM_OUTPUTS, 0);
		configParam(TONE_PARAM, 0.5f, 2.f, 1.f, "Tone");
		configParam(DECAY_PARAM, 0.1f, 1.2f, 0.4f, "Open decay", " s");
		configInput(CH_INPUT, "Closed trigger");
		configInput(OH_INPUT, "Open trigger");
		configInput(TONE_INPUT, "Tone CV");
		configOutput(OUT_OUTPUT, "Audio");
	}

	void process(const ProcessArgs& args) override {
		// Closed chokes open, like the shared hi-hat circuit of the original.
		if (ohTrig.process(inputs[OH_INPUT].getVoltage(), 0.1f, 1.f)) {
			env.trigger();
			open = true;
		}
		if (chTrig.process(inputs[CH_INPUT].getVoltage(), 0.1f, 1.f)) {
			env.trigger();
			open = false;
		}
		float tone = params[TONE_PARAM].getValue() * std::pow(2.f, inputs[TONE_INPUT].getVoltage() / 5.f);
		float base = 320.f * tone;

		float bank = 0.f;
		for (int i = 0; i < 6; i++) {
			phases[i] += base * RATIOS[i] * args.sampleTime;
			if (phases[i] >= 1.f)
				phases[i] -= 1.f;
			bank += (phases[i] < 0.5f) ? 1.f : -1.f;
		}
		bank /= 6.f;

		hp1.setCutoff(5200.f, args.sampleRate);
		hp2.setCutoff(7800.f, args.sampleRate);
		lp.setCutoff(13000.f, args.sampleRate);
		float metal = lp.process(hp2.process(hp1.process(bank)));

		float tau = open ? params[DECAY_PARAM].getValue() : 0.045f;
		float out = metal * env.process(tau, args.sampleTime) * 6.f;
		outputs[OUT_OUTPUT].setVoltage(std::tanh(out) * 5.f);
	}
};

constexpr float HH808::RATIOS[6];

struct HH808Widget : DrumWidget<HH808> {
	HH808Widget(HH808* module) : DrumWidget(module, "res/HH808.svg") {
		addKnobRow(HH808::TONE_PARAM, HH808::TONE_INPUT, 90);
		addKnobRow(HH808::DECAY_PARAM, -1, 165);
		addBottomRow(HH808::CH_INPUT, HH808::OUT_OUTPUT, HH808::OH_INPUT);
	}
};

Model* modelHH808 = createModel<HH808, HH808Widget>("HH808");


// ---- CP-808: handclap -----------------------------------------------------

struct CP808 : Module {
	enum ParamId { TONE_PARAM, DECAY_PARAM, NUM_PARAMS };
	enum InputId { TRIG_INPUT, NUM_INPUTS };
	enum OutputId { OUT_OUTPUT, NUM_OUTPUTS };

	dsp::SchmittTrigger trig;
	float t = 1e9f;
	ExpEnv tail;
	Noise noise;
	OnePoleHP hp;
	OnePoleLP lp;

	CP808() {
		config(NUM_PARAMS, NUM_INPUTS, NUM_OUTPUTS, 0);
		configParam(TONE_PARAM, 400.f, 1600.f, 900.f, "Tone", " Hz");
		configParam(DECAY_PARAM, 0.1f, 0.8f, 0.3f, "Tail", " s");
		configInput(TRIG_INPUT, "Trigger");
		configOutput(OUT_OUTPUT, "Audio");
	}

	void process(const ProcessArgs& args) override {
		if (trig.process(inputs[TRIG_INPUT].getVoltage(), 0.1f, 1.f)) {
			t = 0.f;
			tail.trigger();
		}
		t += args.sampleTime;

		// Three fast retriggered bursts (every 10 ms), then a smooth tail —
		// the multi-spike envelope is what reads as "clap" to the ear.
		float env;
		if (t < 0.03f) {
			float burst = t - std::floor(t / 0.01f) * 0.01f;
			env = std::exp(-burst / 0.004f);
		}
		else {
			env = tail.process(params[DECAY_PARAM].getValue() * 0.4f, args.sampleTime);
		}

		float fc = params[TONE_PARAM].getValue();
		hp.setCutoff(fc, args.sampleRate);
		lp.setCutoff(fc * 4.f, args.sampleRate);
		float n = lp.process(hp.process(noise.next()));

		outputs[OUT_OUTPUT].setVoltage(std::tanh(n * env * 4.f) * 5.f);
	}
};

struct CP808Widget : DrumWidget<CP808> {
	CP808Widget(CP808* module) : DrumWidget(module, "res/CP808.svg") {
		addKnobRow(CP808::TONE_PARAM, -1, 90);
		addKnobRow(CP808::DECAY_PARAM, -1, 165);
		addBottomRow(CP808::TRIG_INPUT, CP808::OUT_OUTPUT);
	}
};

Model* modelCP808 = createModel<CP808, CP808Widget>("CP808");


// ---- CB-808: cowbell ------------------------------------------------------

struct CB808 : Module {
	enum ParamId { TUNE_PARAM, DECAY_PARAM, NUM_PARAMS };
	enum InputId { TRIG_INPUT, NUM_INPUTS };
	enum OutputId { OUT_OUTPUT, NUM_OUTPUTS };

	dsp::SchmittTrigger trig;
	float ph1 = 0.f, ph2 = 0.f;
	ExpEnv env;
	OnePoleHP hp;
	OnePoleLP lp;

	CB808() {
		config(NUM_PARAMS, NUM_INPUTS, NUM_OUTPUTS, 0);
		configParam(TUNE_PARAM, 0.7f, 1.5f, 1.f, "Tune");
		configParam(DECAY_PARAM, 0.05f, 0.6f, 0.2f, "Decay", " s");
		configInput(TRIG_INPUT, "Trigger");
		configOutput(OUT_OUTPUT, "Audio");
	}

	void process(const ProcessArgs& args) override {
		if (trig.process(inputs[TRIG_INPUT].getVoltage(), 0.1f, 1.f))
			env.trigger();
		float tune = params[TUNE_PARAM].getValue();
		// The immortal 540 + 800 Hz pair.
		ph1 += 540.f * tune * args.sampleTime; if (ph1 >= 1.f) ph1 -= 1.f;
		ph2 += 800.f * tune * args.sampleTime; if (ph2 >= 1.f) ph2 -= 1.f;
		float squares = ((ph1 < 0.5f) ? 1.f : -1.f) * 0.5f + ((ph2 < 0.5f) ? 1.f : -1.f) * 0.5f;

		hp.setCutoff(450.f * tune, args.sampleRate);
		lp.setCutoff(1600.f * tune, args.sampleRate);
		float band = lp.process(hp.process(squares));

		float out = band * env.process(params[DECAY_PARAM].getValue(), args.sampleTime) * 4.f;
		outputs[OUT_OUTPUT].setVoltage(std::tanh(out) * 5.f);
	}
};

struct CB808Widget : DrumWidget<CB808> {
	CB808Widget(CB808* module) : DrumWidget(module, "res/CB808.svg") {
		addKnobRow(CB808::TUNE_PARAM, -1, 90);
		addKnobRow(CB808::DECAY_PARAM, -1, 165);
		addBottomRow(CB808::TRIG_INPUT, CB808::OUT_OUTPUT);
	}
};

Model* modelCB808 = createModel<CB808, CB808Widget>("CB808");


// ---- TM-808: tom / conga --------------------------------------------------

struct TM808 : Module {
	enum ParamId { TUNE_PARAM, DECAY_PARAM, NUM_PARAMS };
	enum InputId { TRIG_INPUT, TUNE_INPUT, NUM_INPUTS };
	enum OutputId { OUT_OUTPUT, NUM_OUTPUTS };

	dsp::SchmittTrigger trig;
	float phase = 0.f;
	ExpEnv amp, pitch;
	Noise noise;
	OnePoleLP thumpLp;

	TM808() {
		config(NUM_PARAMS, NUM_INPUTS, NUM_OUTPUTS, 0);
		configParam(TUNE_PARAM, 70.f, 400.f, 160.f, "Tune", " Hz");
		configParam(DECAY_PARAM, 0.05f, 0.8f, 0.3f, "Decay", " s");
		configInput(TRIG_INPUT, "Trigger");
		configInput(TUNE_INPUT, "Tune CV");
		configOutput(OUT_OUTPUT, "Audio");
	}

	void process(const ProcessArgs& args) override {
		if (trig.process(inputs[TRIG_INPUT].getVoltage(), 0.1f, 1.f)) {
			amp.trigger();
			pitch.trigger();
		}
		float f0 = params[TUNE_PARAM].getValue() * std::pow(2.f, inputs[TUNE_INPUT].getVoltage() / 5.f);
		float p = pitch.process(0.06f, args.sampleTime);
		float a = amp.process(params[DECAY_PARAM].getValue(), args.sampleTime);

		float f = f0 * (1.f + 0.8f * p);
		phase += f * args.sampleTime;
		if (phase >= 1.f)
			phase -= 1.f;

		thumpLp.setCutoff(900.f, args.sampleRate);
		float thump = thumpLp.process(noise.next()) * p * 0.6f;

		float out = (std::sin(2.f * M_PI * phase) + thump) * a;
		outputs[OUT_OUTPUT].setVoltage(std::tanh(1.3f * out) * 5.f);
	}
};

struct TM808Widget : DrumWidget<TM808> {
	TM808Widget(TM808* module) : DrumWidget(module, "res/TM808.svg") {
		addKnobRow(TM808::TUNE_PARAM, TM808::TUNE_INPUT, 90);
		addKnobRow(TM808::DECAY_PARAM, -1, 165);
		addBottomRow(TM808::TRIG_INPUT, TM808::OUT_OUTPUT);
	}
};

Model* modelTM808 = createModel<TM808, TM808Widget>("TM808");
